name: Android Debug APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: npm ci || npm install

      - name: Expo prebuild (optional)
        run: |
          if [ ! -d "android" ]; then
            npx expo prebuild --platform android --clean
          fi

      - name: Set Android SDK path
        run: echo "sdk.dir=/usr/lib/android-sdk" > android/local.properties

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew clean :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: android/app/build/outputs/apk/debug/*.apk
